version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    restart: always
    working_dir: /var/www
    volumes:
      - ./project:/var/www:cached
    depends_on:
      - db
      - redis
    env_file:
      - ./project/.env
    command: ["/var/www/entrypoint.sh", "php-fpm"]
    networks:
      - laravel_network

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    volumes:
      - mysqldata:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    networks:
      - laravel_network

  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes
    volumes:
      - redisdata:/data
    networks:
      - laravel_network

  nginx:
    image: nginx:alpine
    container_name: nginx_webserver
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./project:/var/www
    depends_on:
      - app
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  mysqldata:
  redisdata: